name: Deploy to GitHub Pages

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: actions

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "soumya18ranjan.sr@gmail.com"
          git config --global user.name "Soumya Ranjan"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git switch -C gh-pages origin/gh-pages
          rm -rf *
          cp -r ../frontend/build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages