name: Deploy to GitHub Pages

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: actions

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build
      - name: Set up .git-credentials
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # run: |
        #   echo "https://${{ secrets.GH_PAT }}:@github.com" > ~/.git-credentials
        #   git config --global credential.helper store
    #   - name: Deploy to GitHub Pages
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "soumya18ranjan.sr@gmail.com"
          git config --global user.name "Soumya Ranjan"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npx gh-pages --add --dist build --branch actions
          git push --force origin gh-pages